spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myProject
    username: postgres
    password: admin
    hikari:
      schema: last_project_schemas
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS last_project_schemas
      connection-timeout: 10000

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        max.partition.fetch.bytes: 10485760


app:
  jwt:
    secret: "someSecretKey"
    tokenExpiration: 3m
    refreshTokenExpiration: 300m